"""Common constants for acoustic analysis algorithms."""

REFERENCE_PRESSURE_PA = 20e-6

GOLDEN_SAMPLE_CHECKED_KEY = "golden_sample_checked"
GOLDEN_SAMPLE_RESULT_PATH_KEY = "golden_sample_result_path"
GOLDEN_SAMPLE_DISPLAY_MODE_KEY = "golden_sample_display_mode"
GOLDEN_SAMPLE_DISPLAY_MODES_KEY = "golden_sample_display_modes"

GOLDEN_SAMPLE_DISPLAY_DEVIATION = "deviation"
GOLDEN_SAMPLE_DISPLAY_ENVELOPE = "envelope"
GOLDEN_SAMPLE_DISPLAY_MODES = (
    GOLDEN_SAMPLE_DISPLAY_DEVIATION,
    GOLDEN_SAMPLE_DISPLAY_ENVELOPE,
)
DEFAULT_GOLDEN_SAMPLE_DISPLAY_MODE = GOLDEN_SAMPLE_DISPLAY_DEVIATION
DEFAULT_GOLDEN_SAMPLE_DISPLAY_MODES = (GOLDEN_SAMPLE_DISPLAY_DEVIATION,)

GOLDEN_SAMPLE_CURVE_EXPORTS_KEY = "golden_sample_curve_exports"
GOLDEN_SAMPLE_CURVE_EXPORTS_SCHEMA_VERSION = 1

LIMIT_VALUE_SEMANTICS_BOUNDS = "bounds"
LIMIT_VALUE_SEMANTICS_OFFSET = "offset"
