# DO NOT MOVE, UNLESS NECESSARY!!!

- module_name: "preprocess"

  module_config:

    preprocess_method: "None"

- module_name: "model"

  module_config:

    model_name: "CNN1d"

    model_init_config:
      input_len_1: 64340
      input_len_2: 1
      layers_param:
        - layer_name: "Conv1D"
          layer_kwargs:
            filters: 10
            kernel_size: 100
            activation: "relu"
            strides: 10
        - layer_name: "MaxPooling1D"
          layer_kwargs:
            pool_size: 4
        - layer_name: "Conv1D"
          layer_kwargs:
            filters: 20
            kernel_size: 10
            activation: "relu"
            strides: 2
        - layer_name: "MaxPooling1D"
          layer_kwargs:
            pool_size: 4
        - layer_name: "Flatten"
        - layer_name: "Dense"
          layer_kwargs:
            units: 64
            activation: "relu"
        - layer_name: "Dense"
          layer_kwargs:
            units: 1
            activation: "softmax"
      compile_param:
        optimizer: 'adam'
        loss: 'sparse_categorical_crossentropy'
        metrics:
          - accuracy

    model_fit_config:
      balance_sample_number: True

    model_predict_config:
      acc_req: 0.8