# DO NOT MOVE, UNLESS NECESSARY!!!

- module_name: "preprocess"

  module_config:

    preprocess_method: "None" # only mel_spec and mfcc are supported at this moment

- module_name: "model"

  module_config:

    model_name: "RNN"

    model_init_config:
      input_len_1: 64340
      input_len_2: 1
      layers_param:
        - layer_name: "SimpleRNN"
          layer_kwargs:
            units: 64
            return_sequences: True
            activation: "tanh"
        - layer_name: "Flatten"
        - layer_name: "Dense"
          layer_kwargs:
            units: 64
            activation: "relu"
        - layer_name: "Dense"
          layer_kwargs:
            units: 2
            activation: "softmax"
      compile_param:
        optimizer: 'adam'
        loss: 'sparse_categorical_crossentropy'
        metrics:
          - accuracy

    model_fit_config:
      balance_sample_number: True
      cycles: 10
      epochs: 5
      batch_size: 30

    model_predict_config:
      acc_req: 0.8