OK = 0

INVALID_PATH = 10
INVALID_FILE = 11
INVALID_CONFIG = 12

MISSING_MODEL = 20
INVALID_MODEL = 21

INVALID_CONNECT_DATABASE = 60
INVALID_CREATE_TABLE = 61
INVALID_INSERT = 62
INVALID_QUERY = 63
INVALID_DELETE = 64
INVALID_CLOSED = 65
MISSING_SELECT_DATA = 66
INVALID_DATA_LOADING = 67

UNKNOWN_ERROR = 999  # avoid using, unless necessary
