"""Shared raw CSV admission and worker protocol contracts."""

RAW_AUDIO_CSV_CAPACITY = 16
RAW_AUDIO_CSV_PROTOCOL_VERSION = 2
RAW_AUDIO_CSV_READY_TIMEOUT_SECONDS = 30.0
RAW_AUDIO_CSV_SHUTDOWN_TIMEOUT_SECONDS = 5.0
