MAIN_RECORDING_LIVE_WINDOW_SECONDS = 10
MAIN_RECORDING_LIVE_MAX_POINTS = 4_000
MAIN_RECORDING_FINAL_MAX_POINTS = 48_000
PLOT_PRESENTATION_COMPLETE = "complete"
PREVIEW_TIME_MODE_CUMULATIVE = "cumulative"
PREVIEW_TIME_MODE_RELATIVE_LATEST = "relative_latest"
PREVIEW_TIME_LOWER_BOUND_TOLERANCE = 1e-12
RECORDING_PREVIEW_TIME_MODE_CONFIG_KEY = "recording_preview_time_mode"
